#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CellPhone")]
	public partial class DataClassesCellPhoneSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietHDN(ChiTietHDN instance);
    partial void UpdateChiTietHDN(ChiTietHDN instance);
    partial void DeleteChiTietHDN(ChiTietHDN instance);
    partial void InsertQuyen(Quyen instance);
    partial void UpdateQuyen(Quyen instance);
    partial void DeleteQuyen(Quyen instance);
    partial void InsertChiTietHDX(ChiTietHDX instance);
    partial void UpdateChiTietHDX(ChiTietHDX instance);
    partial void DeleteChiTietHDX(ChiTietHDX instance);
    partial void InsertDienThoai(DienThoai instance);
    partial void UpdateDienThoai(DienThoai instance);
    partial void DeleteDienThoai(DienThoai instance);
    partial void InsertGioHang(GioHang instance);
    partial void UpdateGioHang(GioHang instance);
    partial void DeleteGioHang(GioHang instance);
    partial void InsertHoaDonN(HoaDonN instance);
    partial void UpdateHoaDonN(HoaDonN instance);
    partial void DeleteHoaDonN(HoaDonN instance);
    partial void InsertHoaDonX(HoaDonX instance);
    partial void UpdateHoaDonX(HoaDonX instance);
    partial void DeleteHoaDonX(HoaDonX instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLoaiDT(LoaiDT instance);
    partial void UpdateLoaiDT(LoaiDT instance);
    partial void DeleteLoaiDT(LoaiDT instance);
    partial void InsertNhaCC(NhaCC instance);
    partial void UpdateNhaCC(NhaCC instance);
    partial void DeleteNhaCC(NhaCC instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    #endregion
		
		public DataClassesCellPhoneSDataContext() : 
				base(global::DAL.Properties.Settings.Default.CellPhoneConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesCellPhoneSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesCellPhoneSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesCellPhoneSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesCellPhoneSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietHDN> ChiTietHDNs
		{
			get
			{
				return this.GetTable<ChiTietHDN>();
			}
		}
		
		public System.Data.Linq.Table<Quyen> Quyens
		{
			get
			{
				return this.GetTable<Quyen>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietHDX> ChiTietHDXes
		{
			get
			{
				return this.GetTable<ChiTietHDX>();
			}
		}
		
		public System.Data.Linq.Table<DienThoai> DienThoais
		{
			get
			{
				return this.GetTable<DienThoai>();
			}
		}
		
		public System.Data.Linq.Table<GioHang> GioHangs
		{
			get
			{
				return this.GetTable<GioHang>();
			}
		}
		
		public System.Data.Linq.Table<HoaDonN> HoaDonNs
		{
			get
			{
				return this.GetTable<HoaDonN>();
			}
		}
		
		public System.Data.Linq.Table<HoaDonX> HoaDonXes
		{
			get
			{
				return this.GetTable<HoaDonX>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiDT> LoaiDTs
		{
			get
			{
				return this.GetTable<LoaiDT>();
			}
		}
		
		public System.Data.Linq.Table<NhaCC> NhaCCs
		{
			get
			{
				return this.GetTable<NhaCC>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietHDN")]
	public partial class ChiTietHDN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdHDN;
		
		private string _IdDT;
		
		private string _IdNCC;
		
		private string _IdL;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<int> _TongTien;
		
		private EntityRef<DienThoai> _DienThoai;
		
		private EntityRef<HoaDonN> _HoaDonN;
		
		private EntityRef<NhaCC> _NhaCC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdHDNChanging(string value);
    partial void OnIdHDNChanged();
    partial void OnIdDTChanging(string value);
    partial void OnIdDTChanged();
    partial void OnIdNCCChanging(string value);
    partial void OnIdNCCChanged();
    partial void OnIdLChanging(string value);
    partial void OnIdLChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnTongTienChanging(System.Nullable<int> value);
    partial void OnTongTienChanged();
    #endregion
		
		public ChiTietHDN()
		{
			this._DienThoai = default(EntityRef<DienThoai>);
			this._HoaDonN = default(EntityRef<HoaDonN>);
			this._NhaCC = default(EntityRef<NhaCC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHDN", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdHDN
		{
			get
			{
				return this._IdHDN;
			}
			set
			{
				if ((this._IdHDN != value))
				{
					if (this._HoaDonN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdHDNChanging(value);
					this.SendPropertyChanging();
					this._IdHDN = value;
					this.SendPropertyChanged("IdHDN");
					this.OnIdHDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDT", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdDT
		{
			get
			{
				return this._IdDT;
			}
			set
			{
				if ((this._IdDT != value))
				{
					if (this._DienThoai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdDTChanging(value);
					this.SendPropertyChanging();
					this._IdDT = value;
					this.SendPropertyChanged("IdDT");
					this.OnIdDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNCC", DbType="NChar(10)")]
		public string IdNCC
		{
			get
			{
				return this._IdNCC;
			}
			set
			{
				if ((this._IdNCC != value))
				{
					if (this._NhaCC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdNCCChanging(value);
					this.SendPropertyChanging();
					this._IdNCC = value;
					this.SendPropertyChanged("IdNCC");
					this.OnIdNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdL", DbType="NChar(10)")]
		public string IdL
		{
			get
			{
				return this._IdL;
			}
			set
			{
				if ((this._IdL != value))
				{
					this.OnIdLChanging(value);
					this.SendPropertyChanging();
					this._IdL = value;
					this.SendPropertyChanged("IdL");
					this.OnIdLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DienThoai_ChiTietHDN", Storage="_DienThoai", ThisKey="IdDT", OtherKey="IdDT", IsForeignKey=true)]
		public DienThoai DienThoai
		{
			get
			{
				return this._DienThoai.Entity;
			}
			set
			{
				DienThoai previousValue = this._DienThoai.Entity;
				if (((previousValue != value) 
							|| (this._DienThoai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DienThoai.Entity = null;
						previousValue.ChiTietHDNs.Remove(this);
					}
					this._DienThoai.Entity = value;
					if ((value != null))
					{
						value.ChiTietHDNs.Add(this);
						this._IdDT = value.IdDT;
					}
					else
					{
						this._IdDT = default(string);
					}
					this.SendPropertyChanged("DienThoai");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDonN_ChiTietHDN", Storage="_HoaDonN", ThisKey="IdHDN", OtherKey="IdHDN", IsForeignKey=true)]
		public HoaDonN HoaDonN
		{
			get
			{
				return this._HoaDonN.Entity;
			}
			set
			{
				HoaDonN previousValue = this._HoaDonN.Entity;
				if (((previousValue != value) 
							|| (this._HoaDonN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDonN.Entity = null;
						previousValue.ChiTietHDNs.Remove(this);
					}
					this._HoaDonN.Entity = value;
					if ((value != null))
					{
						value.ChiTietHDNs.Add(this);
						this._IdHDN = value.IdHDN;
					}
					else
					{
						this._IdHDN = default(string);
					}
					this.SendPropertyChanged("HoaDonN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCC_ChiTietHDN", Storage="_NhaCC", ThisKey="IdNCC", OtherKey="IdNCC", IsForeignKey=true)]
		public NhaCC NhaCC
		{
			get
			{
				return this._NhaCC.Entity;
			}
			set
			{
				NhaCC previousValue = this._NhaCC.Entity;
				if (((previousValue != value) 
							|| (this._NhaCC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaCC.Entity = null;
						previousValue.ChiTietHDNs.Remove(this);
					}
					this._NhaCC.Entity = value;
					if ((value != null))
					{
						value.ChiTietHDNs.Add(this);
						this._IdNCC = value.IdNCC;
					}
					else
					{
						this._IdNCC = default(string);
					}
					this.SendPropertyChanged("NhaCC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Quyen")]
	public partial class Quyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _Tenquyen;
		
		private string _Mota;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnTenquyenChanging(string value);
    partial void OnTenquyenChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    #endregion
		
		public Quyen()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenquyen", DbType="NVarChar(50)")]
		public string Tenquyen
		{
			get
			{
				return this._Tenquyen;
			}
			set
			{
				if ((this._Tenquyen != value))
				{
					this.OnTenquyenChanging(value);
					this.SendPropertyChanging();
					this._Tenquyen = value;
					this.SendPropertyChanged("Tenquyen");
					this.OnTenquyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(MAX)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Quyen_NhanVien", Storage="_NhanViens", ThisKey="ID", OtherKey="ID")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.Quyen = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.Quyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietHDX")]
	public partial class ChiTietHDX : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdHDX;
		
		private string _IdC;
		
		private string _IdDT;
		
		private string _IdL;
		
		private System.Nullable<int> _TongTien;
		
		private EntityRef<DienThoai> _DienThoai;
		
		private EntityRef<HoaDonX> _HoaDonX;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdHDXChanging(string value);
    partial void OnIdHDXChanged();
    partial void OnIdCChanging(string value);
    partial void OnIdCChanged();
    partial void OnIdDTChanging(string value);
    partial void OnIdDTChanged();
    partial void OnIdLChanging(string value);
    partial void OnIdLChanged();
    partial void OnTongTienChanging(System.Nullable<int> value);
    partial void OnTongTienChanged();
    #endregion
		
		public ChiTietHDX()
		{
			this._DienThoai = default(EntityRef<DienThoai>);
			this._HoaDonX = default(EntityRef<HoaDonX>);
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHDX", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdHDX
		{
			get
			{
				return this._IdHDX;
			}
			set
			{
				if ((this._IdHDX != value))
				{
					if (this._HoaDonX.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdHDXChanging(value);
					this.SendPropertyChanging();
					this._IdHDX = value;
					this.SendPropertyChanged("IdHDX");
					this.OnIdHDXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdC", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string IdC
		{
			get
			{
				return this._IdC;
			}
			set
			{
				if ((this._IdC != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCChanging(value);
					this.SendPropertyChanging();
					this._IdC = value;
					this.SendPropertyChanged("IdC");
					this.OnIdCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDT", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdDT
		{
			get
			{
				return this._IdDT;
			}
			set
			{
				if ((this._IdDT != value))
				{
					if (this._DienThoai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdDTChanging(value);
					this.SendPropertyChanging();
					this._IdDT = value;
					this.SendPropertyChanged("IdDT");
					this.OnIdDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdL", DbType="NChar(10)")]
		public string IdL
		{
			get
			{
				return this._IdL;
			}
			set
			{
				if ((this._IdL != value))
				{
					this.OnIdLChanging(value);
					this.SendPropertyChanging();
					this._IdL = value;
					this.SendPropertyChanged("IdL");
					this.OnIdLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DienThoai_ChiTietHDX", Storage="_DienThoai", ThisKey="IdDT", OtherKey="IdDT", IsForeignKey=true)]
		public DienThoai DienThoai
		{
			get
			{
				return this._DienThoai.Entity;
			}
			set
			{
				DienThoai previousValue = this._DienThoai.Entity;
				if (((previousValue != value) 
							|| (this._DienThoai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DienThoai.Entity = null;
						previousValue.ChiTietHDXes.Remove(this);
					}
					this._DienThoai.Entity = value;
					if ((value != null))
					{
						value.ChiTietHDXes.Add(this);
						this._IdDT = value.IdDT;
					}
					else
					{
						this._IdDT = default(string);
					}
					this.SendPropertyChanged("DienThoai");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDonX_ChiTietHDX", Storage="_HoaDonX", ThisKey="IdHDX", OtherKey="IdHDX", IsForeignKey=true)]
		public HoaDonX HoaDonX
		{
			get
			{
				return this._HoaDonX.Entity;
			}
			set
			{
				HoaDonX previousValue = this._HoaDonX.Entity;
				if (((previousValue != value) 
							|| (this._HoaDonX.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDonX.Entity = null;
						previousValue.ChiTietHDXes.Remove(this);
					}
					this._HoaDonX.Entity = value;
					if ((value != null))
					{
						value.ChiTietHDXes.Add(this);
						this._IdHDX = value.IdHDX;
					}
					else
					{
						this._IdHDX = default(string);
					}
					this.SendPropertyChanged("HoaDonX");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_ChiTietHDX", Storage="_KhachHang", ThisKey="IdC", OtherKey="IdC", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.ChiTietHDXes.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.ChiTietHDXes.Add(this);
						this._IdC = value.IdC;
					}
					else
					{
						this._IdC = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DienThoai")]
	public partial class DienThoai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdDT;
		
		private string _TenDT;
		
		private string _IdL;
		
		private string _Mau;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<int> _GiaNhap;
		
		private System.Nullable<int> _GiaBan;
		
		private string _Anh;
		
		private string _Network;
		
		private string _SIM;
		
		private string _ManHinh;
		
		private string _RAM;
		
		private string _SDcard;
		
		private string _CPU;
		
		private string _Camera;
		
		private string _Pin;
		
		private System.Nullable<int> _Talktime;
		
		private System.Nullable<int> _WaitTime;
		
		private EntitySet<ChiTietHDN> _ChiTietHDNs;
		
		private EntitySet<ChiTietHDX> _ChiTietHDXes;
		
		private EntityRef<LoaiDT> _LoaiDT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDTChanging(string value);
    partial void OnIdDTChanged();
    partial void OnTenDTChanging(string value);
    partial void OnTenDTChanged();
    partial void OnIdLChanging(string value);
    partial void OnIdLChanged();
    partial void OnMauChanging(string value);
    partial void OnMauChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnGiaNhapChanging(System.Nullable<int> value);
    partial void OnGiaNhapChanged();
    partial void OnGiaBanChanging(System.Nullable<int> value);
    partial void OnGiaBanChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnNetworkChanging(string value);
    partial void OnNetworkChanged();
    partial void OnSIMChanging(string value);
    partial void OnSIMChanged();
    partial void OnManHinhChanging(string value);
    partial void OnManHinhChanged();
    partial void OnRAMChanging(string value);
    partial void OnRAMChanged();
    partial void OnSDcardChanging(string value);
    partial void OnSDcardChanged();
    partial void OnCPUChanging(string value);
    partial void OnCPUChanged();
    partial void OnCameraChanging(string value);
    partial void OnCameraChanged();
    partial void OnPinChanging(string value);
    partial void OnPinChanged();
    partial void OnTalktimeChanging(System.Nullable<int> value);
    partial void OnTalktimeChanged();
    partial void OnWaitTimeChanging(System.Nullable<int> value);
    partial void OnWaitTimeChanged();
    #endregion
		
		public DienThoai()
		{
			this._ChiTietHDNs = new EntitySet<ChiTietHDN>(new Action<ChiTietHDN>(this.attach_ChiTietHDNs), new Action<ChiTietHDN>(this.detach_ChiTietHDNs));
			this._ChiTietHDXes = new EntitySet<ChiTietHDX>(new Action<ChiTietHDX>(this.attach_ChiTietHDXes), new Action<ChiTietHDX>(this.detach_ChiTietHDXes));
			this._LoaiDT = default(EntityRef<LoaiDT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDT", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdDT
		{
			get
			{
				return this._IdDT;
			}
			set
			{
				if ((this._IdDT != value))
				{
					this.OnIdDTChanging(value);
					this.SendPropertyChanging();
					this._IdDT = value;
					this.SendPropertyChanged("IdDT");
					this.OnIdDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDT", DbType="NVarChar(100)")]
		public string TenDT
		{
			get
			{
				return this._TenDT;
			}
			set
			{
				if ((this._TenDT != value))
				{
					this.OnTenDTChanging(value);
					this.SendPropertyChanging();
					this._TenDT = value;
					this.SendPropertyChanged("TenDT");
					this.OnTenDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdL", DbType="NChar(10)")]
		public string IdL
		{
			get
			{
				return this._IdL;
			}
			set
			{
				if ((this._IdL != value))
				{
					if (this._LoaiDT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdLChanging(value);
					this.SendPropertyChanging();
					this._IdL = value;
					this.SendPropertyChanged("IdL");
					this.OnIdLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mau", DbType="NVarChar(50)")]
		public string Mau
		{
			get
			{
				return this._Mau;
			}
			set
			{
				if ((this._Mau != value))
				{
					this.OnMauChanging(value);
					this.SendPropertyChanging();
					this._Mau = value;
					this.SendPropertyChanged("Mau");
					this.OnMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaNhap", DbType="Int")]
		public System.Nullable<int> GiaNhap
		{
			get
			{
				return this._GiaNhap;
			}
			set
			{
				if ((this._GiaNhap != value))
				{
					this.OnGiaNhapChanging(value);
					this.SendPropertyChanging();
					this._GiaNhap = value;
					this.SendPropertyChanged("GiaNhap");
					this.OnGiaNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="Int")]
		public System.Nullable<int> GiaBan
		{
			get
			{
				return this._GiaBan;
			}
			set
			{
				if ((this._GiaBan != value))
				{
					this.OnGiaBanChanging(value);
					this.SendPropertyChanging();
					this._GiaBan = value;
					this.SendPropertyChanged("GiaBan");
					this.OnGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="NVarChar(100)")]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Network", DbType="NVarChar(200)")]
		public string Network
		{
			get
			{
				return this._Network;
			}
			set
			{
				if ((this._Network != value))
				{
					this.OnNetworkChanging(value);
					this.SendPropertyChanging();
					this._Network = value;
					this.SendPropertyChanged("Network");
					this.OnNetworkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIM", DbType="NVarChar(50)")]
		public string SIM
		{
			get
			{
				return this._SIM;
			}
			set
			{
				if ((this._SIM != value))
				{
					this.OnSIMChanging(value);
					this.SendPropertyChanging();
					this._SIM = value;
					this.SendPropertyChanged("SIM");
					this.OnSIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManHinh", DbType="NVarChar(50)")]
		public string ManHinh
		{
			get
			{
				return this._ManHinh;
			}
			set
			{
				if ((this._ManHinh != value))
				{
					this.OnManHinhChanging(value);
					this.SendPropertyChanging();
					this._ManHinh = value;
					this.SendPropertyChanged("ManHinh");
					this.OnManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAM", DbType="NVarChar(50)")]
		public string RAM
		{
			get
			{
				return this._RAM;
			}
			set
			{
				if ((this._RAM != value))
				{
					this.OnRAMChanging(value);
					this.SendPropertyChanging();
					this._RAM = value;
					this.SendPropertyChanged("RAM");
					this.OnRAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDcard", DbType="NVarChar(100)")]
		public string SDcard
		{
			get
			{
				return this._SDcard;
			}
			set
			{
				if ((this._SDcard != value))
				{
					this.OnSDcardChanging(value);
					this.SendPropertyChanging();
					this._SDcard = value;
					this.SendPropertyChanged("SDcard");
					this.OnSDcardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPU", DbType="NVarChar(200)")]
		public string CPU
		{
			get
			{
				return this._CPU;
			}
			set
			{
				if ((this._CPU != value))
				{
					this.OnCPUChanging(value);
					this.SendPropertyChanging();
					this._CPU = value;
					this.SendPropertyChanged("CPU");
					this.OnCPUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Camera", DbType="NVarChar(150)")]
		public string Camera
		{
			get
			{
				return this._Camera;
			}
			set
			{
				if ((this._Camera != value))
				{
					this.OnCameraChanging(value);
					this.SendPropertyChanging();
					this._Camera = value;
					this.SendPropertyChanged("Camera");
					this.OnCameraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pin", DbType="NVarChar(50)")]
		public string Pin
		{
			get
			{
				return this._Pin;
			}
			set
			{
				if ((this._Pin != value))
				{
					this.OnPinChanging(value);
					this.SendPropertyChanging();
					this._Pin = value;
					this.SendPropertyChanged("Pin");
					this.OnPinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Talktime", DbType="Int")]
		public System.Nullable<int> Talktime
		{
			get
			{
				return this._Talktime;
			}
			set
			{
				if ((this._Talktime != value))
				{
					this.OnTalktimeChanging(value);
					this.SendPropertyChanging();
					this._Talktime = value;
					this.SendPropertyChanged("Talktime");
					this.OnTalktimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaitTime", DbType="Int")]
		public System.Nullable<int> WaitTime
		{
			get
			{
				return this._WaitTime;
			}
			set
			{
				if ((this._WaitTime != value))
				{
					this.OnWaitTimeChanging(value);
					this.SendPropertyChanging();
					this._WaitTime = value;
					this.SendPropertyChanged("WaitTime");
					this.OnWaitTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DienThoai_ChiTietHDN", Storage="_ChiTietHDNs", ThisKey="IdDT", OtherKey="IdDT")]
		public EntitySet<ChiTietHDN> ChiTietHDNs
		{
			get
			{
				return this._ChiTietHDNs;
			}
			set
			{
				this._ChiTietHDNs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DienThoai_ChiTietHDX", Storage="_ChiTietHDXes", ThisKey="IdDT", OtherKey="IdDT")]
		public EntitySet<ChiTietHDX> ChiTietHDXes
		{
			get
			{
				return this._ChiTietHDXes;
			}
			set
			{
				this._ChiTietHDXes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiDT_DienThoai", Storage="_LoaiDT", ThisKey="IdL", OtherKey="IdL", IsForeignKey=true)]
		public LoaiDT LoaiDT
		{
			get
			{
				return this._LoaiDT.Entity;
			}
			set
			{
				LoaiDT previousValue = this._LoaiDT.Entity;
				if (((previousValue != value) 
							|| (this._LoaiDT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiDT.Entity = null;
						previousValue.DienThoais.Remove(this);
					}
					this._LoaiDT.Entity = value;
					if ((value != null))
					{
						value.DienThoais.Add(this);
						this._IdL = value.IdL;
					}
					else
					{
						this._IdL = default(string);
					}
					this.SendPropertyChanged("LoaiDT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHDNs(ChiTietHDN entity)
		{
			this.SendPropertyChanging();
			entity.DienThoai = this;
		}
		
		private void detach_ChiTietHDNs(ChiTietHDN entity)
		{
			this.SendPropertyChanging();
			entity.DienThoai = null;
		}
		
		private void attach_ChiTietHDXes(ChiTietHDX entity)
		{
			this.SendPropertyChanging();
			entity.DienThoai = this;
		}
		
		private void detach_ChiTietHDXes(ChiTietHDX entity)
		{
			this.SendPropertyChanging();
			entity.DienThoai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GioHang")]
	public partial class GioHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdCart;
		
		private string _IdC;
		
		private string _IdDT;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<int> _TongTien;
		
		private System.Nullable<System.DateTime> _NgayDat;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCartChanging(string value);
    partial void OnIdCartChanged();
    partial void OnIdCChanging(string value);
    partial void OnIdCChanged();
    partial void OnIdDTChanging(string value);
    partial void OnIdDTChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnTongTienChanging(System.Nullable<int> value);
    partial void OnTongTienChanged();
    partial void OnNgayDatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatChanged();
    #endregion
		
		public GioHang()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCart", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdCart
		{
			get
			{
				return this._IdCart;
			}
			set
			{
				if ((this._IdCart != value))
				{
					this.OnIdCartChanging(value);
					this.SendPropertyChanging();
					this._IdCart = value;
					this.SendPropertyChanged("IdCart");
					this.OnIdCartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdC", DbType="NChar(10)")]
		public string IdC
		{
			get
			{
				return this._IdC;
			}
			set
			{
				if ((this._IdC != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCChanging(value);
					this.SendPropertyChanging();
					this._IdC = value;
					this.SendPropertyChanged("IdC");
					this.OnIdCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDT", DbType="NChar(10)")]
		public string IdDT
		{
			get
			{
				return this._IdDT;
			}
			set
			{
				if ((this._IdDT != value))
				{
					this.OnIdDTChanging(value);
					this.SendPropertyChanging();
					this._IdDT = value;
					this.SendPropertyChanged("IdDT");
					this.OnIdDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDat
		{
			get
			{
				return this._NgayDat;
			}
			set
			{
				if ((this._NgayDat != value))
				{
					this.OnNgayDatChanging(value);
					this.SendPropertyChanging();
					this._NgayDat = value;
					this.SendPropertyChanged("NgayDat");
					this.OnNgayDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_GioHang", Storage="_KhachHang", ThisKey="IdC", OtherKey="IdC", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.GioHangs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.GioHangs.Add(this);
						this._IdC = value.IdC;
					}
					else
					{
						this._IdC = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDonN")]
	public partial class HoaDonN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdHDN;
		
		private System.Nullable<System.DateTime> _NgayNhap;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<int> _TongTien;
		
		private EntitySet<ChiTietHDN> _ChiTietHDNs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdHDNChanging(string value);
    partial void OnIdHDNChanged();
    partial void OnNgayNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhapChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnTongTienChanging(System.Nullable<int> value);
    partial void OnTongTienChanged();
    #endregion
		
		public HoaDonN()
		{
			this._ChiTietHDNs = new EntitySet<ChiTietHDN>(new Action<ChiTietHDN>(this.attach_ChiTietHDNs), new Action<ChiTietHDN>(this.detach_ChiTietHDNs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHDN", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdHDN
		{
			get
			{
				return this._IdHDN;
			}
			set
			{
				if ((this._IdHDN != value))
				{
					this.OnIdHDNChanging(value);
					this.SendPropertyChanging();
					this._IdHDN = value;
					this.SendPropertyChanged("IdHDN");
					this.OnIdHDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDonN_ChiTietHDN", Storage="_ChiTietHDNs", ThisKey="IdHDN", OtherKey="IdHDN")]
		public EntitySet<ChiTietHDN> ChiTietHDNs
		{
			get
			{
				return this._ChiTietHDNs;
			}
			set
			{
				this._ChiTietHDNs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHDNs(ChiTietHDN entity)
		{
			this.SendPropertyChanging();
			entity.HoaDonN = this;
		}
		
		private void detach_ChiTietHDNs(ChiTietHDN entity)
		{
			this.SendPropertyChanging();
			entity.HoaDonN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDonX")]
	public partial class HoaDonX : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdHDX;
		
		private System.Nullable<System.DateTime> _NgayXuat;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<int> _TongTien;
		
		private EntitySet<ChiTietHDX> _ChiTietHDXes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdHDXChanging(string value);
    partial void OnIdHDXChanged();
    partial void OnNgayXuatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXuatChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnTongTienChanging(System.Nullable<int> value);
    partial void OnTongTienChanged();
    #endregion
		
		public HoaDonX()
		{
			this._ChiTietHDXes = new EntitySet<ChiTietHDX>(new Action<ChiTietHDX>(this.attach_ChiTietHDXes), new Action<ChiTietHDX>(this.detach_ChiTietHDXes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHDX", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdHDX
		{
			get
			{
				return this._IdHDX;
			}
			set
			{
				if ((this._IdHDX != value))
				{
					this.OnIdHDXChanging(value);
					this.SendPropertyChanging();
					this._IdHDX = value;
					this.SendPropertyChanged("IdHDX");
					this.OnIdHDXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXuat", DbType="Date")]
		public System.Nullable<System.DateTime> NgayXuat
		{
			get
			{
				return this._NgayXuat;
			}
			set
			{
				if ((this._NgayXuat != value))
				{
					this.OnNgayXuatChanging(value);
					this.SendPropertyChanging();
					this._NgayXuat = value;
					this.SendPropertyChanged("NgayXuat");
					this.OnNgayXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDonX_ChiTietHDX", Storage="_ChiTietHDXes", ThisKey="IdHDX", OtherKey="IdHDX")]
		public EntitySet<ChiTietHDX> ChiTietHDXes
		{
			get
			{
				return this._ChiTietHDXes;
			}
			set
			{
				this._ChiTietHDXes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHDXes(ChiTietHDX entity)
		{
			this.SendPropertyChanging();
			entity.HoaDonX = this;
		}
		
		private void detach_ChiTietHDXes(ChiTietHDX entity)
		{
			this.SendPropertyChanging();
			entity.HoaDonX = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdC;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private string _SDT;
		
		private string _Email;
		
		private string _DiaChi;
		
		private EntitySet<ChiTietHDX> _ChiTietHDXes;
		
		private EntitySet<GioHang> _GioHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCChanging(string value);
    partial void OnIdCChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public KhachHang()
		{
			this._ChiTietHDXes = new EntitySet<ChiTietHDX>(new Action<ChiTietHDX>(this.attach_ChiTietHDXes), new Action<ChiTietHDX>(this.detach_ChiTietHDXes));
			this._GioHangs = new EntitySet<GioHang>(new Action<GioHang>(this.attach_GioHangs), new Action<GioHang>(this.detach_GioHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdC", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdC
		{
			get
			{
				return this._IdC;
			}
			set
			{
				if ((this._IdC != value))
				{
					this.OnIdCChanging(value);
					this.SendPropertyChanging();
					this._IdC = value;
					this.SendPropertyChanged("IdC");
					this.OnIdCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(150)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(200)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_ChiTietHDX", Storage="_ChiTietHDXes", ThisKey="IdC", OtherKey="IdC")]
		public EntitySet<ChiTietHDX> ChiTietHDXes
		{
			get
			{
				return this._ChiTietHDXes;
			}
			set
			{
				this._ChiTietHDXes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_GioHang", Storage="_GioHangs", ThisKey="IdC", OtherKey="IdC")]
		public EntitySet<GioHang> GioHangs
		{
			get
			{
				return this._GioHangs;
			}
			set
			{
				this._GioHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHDXes(ChiTietHDX entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_ChiTietHDXes(ChiTietHDX entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_GioHangs(GioHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_GioHangs(GioHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiDT")]
	public partial class LoaiDT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdL;
		
		private string _TenLoai;
		
		private System.Nullable<int> _SoLuong;
		
		private EntitySet<DienThoai> _DienThoais;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdLChanging(string value);
    partial void OnIdLChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
		
		public LoaiDT()
		{
			this._DienThoais = new EntitySet<DienThoai>(new Action<DienThoai>(this.attach_DienThoais), new Action<DienThoai>(this.detach_DienThoais));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdL", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdL
		{
			get
			{
				return this._IdL;
			}
			set
			{
				if ((this._IdL != value))
				{
					this.OnIdLChanging(value);
					this.SendPropertyChanging();
					this._IdL = value;
					this.SendPropertyChanged("IdL");
					this.OnIdLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(100)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiDT_DienThoai", Storage="_DienThoais", ThisKey="IdL", OtherKey="IdL")]
		public EntitySet<DienThoai> DienThoais
		{
			get
			{
				return this._DienThoais;
			}
			set
			{
				this._DienThoais.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DienThoais(DienThoai entity)
		{
			this.SendPropertyChanging();
			entity.LoaiDT = this;
		}
		
		private void detach_DienThoais(DienThoai entity)
		{
			this.SendPropertyChanging();
			entity.LoaiDT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaCC")]
	public partial class NhaCC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdNCC;
		
		private string _TenNCC;
		
		private string _SDT;
		
		private string _DiaChi;
		
		private EntitySet<ChiTietHDN> _ChiTietHDNs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdNCCChanging(string value);
    partial void OnIdNCCChanged();
    partial void OnTenNCCChanging(string value);
    partial void OnTenNCCChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public NhaCC()
		{
			this._ChiTietHDNs = new EntitySet<ChiTietHDN>(new Action<ChiTietHDN>(this.attach_ChiTietHDNs), new Action<ChiTietHDN>(this.detach_ChiTietHDNs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNCC", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdNCC
		{
			get
			{
				return this._IdNCC;
			}
			set
			{
				if ((this._IdNCC != value))
				{
					this.OnIdNCCChanging(value);
					this.SendPropertyChanging();
					this._IdNCC = value;
					this.SendPropertyChanged("IdNCC");
					this.OnIdNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNCC", DbType="NChar(10)")]
		public string TenNCC
		{
			get
			{
				return this._TenNCC;
			}
			set
			{
				if ((this._TenNCC != value))
				{
					this.OnTenNCCChanging(value);
					this.SendPropertyChanging();
					this._TenNCC = value;
					this.SendPropertyChanged("TenNCC");
					this.OnTenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(200)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCC_ChiTietHDN", Storage="_ChiTietHDNs", ThisKey="IdNCC", OtherKey="IdNCC")]
		public EntitySet<ChiTietHDN> ChiTietHDNs
		{
			get
			{
				return this._ChiTietHDNs;
			}
			set
			{
				this._ChiTietHDNs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHDNs(ChiTietHDN entity)
		{
			this.SendPropertyChanging();
			entity.NhaCC = this;
		}
		
		private void detach_ChiTietHDNs(ChiTietHDN entity)
		{
			this.SendPropertyChanging();
			entity.NhaCC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdNV;
		
		private string _TenNV;
		
		private string _ChucVu;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private string _Email;
		
		private string _username;
		
		private string _password;
		
		private string _status;
		
		private string _ID;
		
		private EntityRef<Quyen> _Quyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdNVChanging(string value);
    partial void OnIdNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    #endregion
		
		public NhanVien()
		{
			this._Quyen = default(EntityRef<Quyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdNV
		{
			get
			{
				return this._IdNV;
			}
			set
			{
				if ((this._IdNV != value))
				{
					this.OnIdNVChanging(value);
					this.SendPropertyChanging();
					this._IdNV = value;
					this.SendPropertyChanged("IdNV");
					this.OnIdNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(200)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(150)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(200)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NChar(10)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NChar(10)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._Quyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Quyen_NhanVien", Storage="_Quyen", ThisKey="ID", OtherKey="ID", IsForeignKey=true)]
		public Quyen Quyen
		{
			get
			{
				return this._Quyen.Entity;
			}
			set
			{
				Quyen previousValue = this._Quyen.Entity;
				if (((previousValue != value) 
							|| (this._Quyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Quyen.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._Quyen.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._ID = value.ID;
					}
					else
					{
						this._ID = default(string);
					}
					this.SendPropertyChanged("Quyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
